### ISSUE TITLE
Proper way to check for count?

### ISSUE THREAD

**Issue by josebalius** [istreamdata/orientgo#43]
Let's say I do a query that might return 0 records, what is the proper way to check if the query return any results? 

At the moment I am having to catch this in an error from c.All, for example:

``` Go
c := orient.Command(orient.NewSQLQuery("select * from Test"))

if err := c.Err(); err != nil {
   panic(err);
}

var recs []MyStruct
if err := c.All(&recs); err != nil {
   panic(err) // i get the no records returned error here but would like to have a better way to detect no records returned
}
```

**Comment by dennwc** [comment]
Looks like a bug in logic. It should return such errors only for non-slice destination types.

**Comment by dennwc** [comment]
Can't reproduce with slice on latest driver version. Maybe you have tried to load results into a single value?

I pushed a commit 7e83f38e8d2fa4424da4d00513b5dfa004ee5f00 to expose error types from results converter, so you can match returned errors to these (`ErrNoRecord` and `ErrMultipleRecords`).

**Comment by josebalius** [comment]
@dennwc sorry, it wasn't a slice i posted the wrong example, yes I have a single struct. So i guess I just have to check the error type and that's how to handle no results being returned? Would it help if I limited the query to 1 result?

**Comment by dennwc** [comment]
Yes, you have to check that error. This behavior is intentional. If the result set is empty and an error is nil, how can you know, that it was an empty result set and not a empty object from a database that was successively deserialized into your value? The same stands for multiple results. If you have multiple results and your code trying to deserialize them into a single struct, there is definitely something wrong with query/database or it was just a programmer's mistake.

**Comment by josebalius** [comment]
@dennwc I kept thinking that adding a Count() method to the Results interface that Command returns might be useful, I understand that Command can do other operations that don't really return a count but I have used an orient REST library that used internally at first that provided this count for queries and it was quite nice to have that info available. What do you think? I wouldn't mind working on a PR for this.

**Comment by dennwc** [comment]
In fact, implementation of such function is easy enough. Result object just stores records slice inside itself, so potentially we can just grab records count directly. But there is some other points to consider:
- OrientDB now supports result streaming, and in this case we just can't provide any useful number for Count. There might be other such cases.
- Count function might be used for results count from SELECT queries, or as an affected rows count for UPDATE. This functionality is harder to implement in a right way, because there may be a case than we want to return a single int from server-side function, and, for driver perspective, this result is similar to updated records count.
